In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Load data

In [107]:
train = pd.read_csv('Higgstrain.csv')

X_train = train.drop(['Label', 'Unnamed: 0'], axis=1)
Y_train = train['Label'].replace(['b','s'], [0,1])

In [108]:
X_train = (X_train - X_train.mean())/X_train.std()

In [109]:
X_train.head()

DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0     -0.308320                    -1.113654     -0.330946 -1.169774   
1     -0.374869                    -1.137812      0.032758  0.518143   
2      0.336438                    -1.005717      0.375088 -0.498063   
3     -0.998698                     0.507690     -0.807072 -0.197100   
4     -1.070064                    -0.815299     -1.211067  1.093629   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0              1.122594          0.551529            -0.545225   
1             -0.725860         -0.655357             0.187956   
2             -0.853773         -0.737107             0.185173   
3             -0.082870         -0.257753             0.208824   
4              1.504619          3.184626            -1.519924   

   DER_deltar_tau_lep  DER_pt_tot  DER_sum_pt       ...        PRI_met_phi  \
0            1.093017    0.290408   -0.391853       ...           1.562832   
1           -1.102991    1.224285    0.447762       ...          -1.253904   
2            0.452676   -0.905403   -0.637879       ...          -0.879294   
3           -1.144303    1.330976   -0.091642       ...           0.145925   
4           -1.722676   -0.961516    0.581693       ...          -1.007102   

   PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
0      -0.680590     1.516787           -0.606501            -0.446520   
1       0.279613     1.516787           -0.264872             0.130893   
2      -0.747570    -0.659276           -0.547377            -0.289148   
3       0.512544    -0.659276            0.271973            -0.030485   
4      -0.230254    -0.659276            0.802312            -1.283741   

   PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0             0.689169               0.234759                1.772501   
1             0.136267              -0.501999               -0.457752   
2             0.492532              -0.817951                0.213575   
3            -0.740312               0.162450                1.095303   
4             1.085203               1.510687                1.383993   

   PRI_jet_subleading_phi  PRI_jet_all_pt  
0               -1.165809       -0.154394  
1                1.004541        0.115269  
2               -0.401035       -0.759244  
3               -1.442957        0.048600  
4                0.222135        0.784257  

[5 rows x 30 columns]

In [11]:
test= pd.read_csv('Higgstest.csv')
X_test = test.drop(['Label', 'Unnamed: 0'], axis=1)
Y_test = test['Label'].replace(['b','s'], [0,1])

In [13]:
X_test = (X_test-X_test.mean())/X_test.std()
X_test.head()

DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0     -0.204430                    -0.790581     -0.494535  0.222767   
1      0.081960                     0.407730      0.538884  0.625440   
2      1.258408                     1.416947      0.419246 -0.383206   
3     -0.499936                     0.423774     -0.333164  0.282787   
4     -0.178375                     1.809161      0.344524 -0.085409   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0             -1.054271         -0.832179             0.493412   
1              0.978016          2.140250            -0.951336   
2             -0.213679         -0.671696             0.862752   
3             -0.911885         -0.803288             0.296895   
4             -0.949626         -0.774088             0.364909   

   DER_deltar_tau_lep  DER_pt_tot  DER_sum_pt       ...        PRI_met_phi  \
0           -0.278981   -0.164827   -0.500498       ...           1.652916   
1           -0.791332   -0.922031    1.434082       ...          -1.513565   
2            1.529089   -0.862622   -0.802835       ...          -0.118588   
3           -0.855860   -0.922311   -0.258084       ...          -0.850080   
4           -0.751325   -0.775655   -0.202205       ...          -0.437061   

   PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
0      -0.253251     -0.66507           -0.335862             0.405766   
1       0.405832     -0.66507            0.718603             1.218404   
2      -0.772349     -0.66507           -0.765130             1.630462   
3       0.035088     -0.66507           -0.099468             0.591135   
4      -0.081456     -0.66507           -0.549656             0.223267   

   PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0            -0.232734              -0.042087                0.646186   
1            -0.800166               2.930148               -0.968661   
2            -1.364827              -0.833181                0.401246   
3             1.009632              -0.700604                0.112793   
4             0.278731              -0.422695                0.580673   

   PRI_jet_subleading_phi  PRI_jet_all_pt  
0               -0.293286       -0.397762  
1                0.334115        1.143275  
2                1.631072       -0.901528  
3                1.209520       -0.443151  
4                0.779756       -0.644709  

[5 rows x 30 columns]

In [56]:
algo = ['SVM', 'RM', 'LR', 'GB', 'LDA', 'QDA', 'NB', 'NN']

d = { 'CV-5 mean accuracy': 
pd.Series([0.83386245968105932, 'NaN', 0.72690904361508391, 0.8438457526169435,0.72689069162389297, 0.72246795772478478, 0.72692739560627495, 0.800994590701], index = algo
        )}

score = pd.DataFrame(d)

In [60]:
score['Test accuracy'] = [0.83814137855097992, 0.84540850033032366, 0.73515378404169418, 0.8472436320927843, 0.72415628268888443, 'NaN',0.73500697350069732, 0.81032078103207805]

#  Classifying Algorithms 

In [19]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report,confusion_matrix

In [23]:
def AMS2 (confusmat):
    """
    Input:   Confusion Matrix
    Output:  AMS2 score
    """
    
    tn, fp, fn, tp = confusmat.ravel()
    s= tp/(tp+fn) 
    b= fp/(fp+tn)
    
    return np.sqrt( 2 *( (s+b)*np.log(1 +s/b) -s) )

### SVM 

In [16]:
from sklearn import svm
from sklearn.model_selection import cross_val_score

clf_SVM = svm.SVC()
cross_val_score(clf_SVM, X_train, Y_train, cv=5).mean() 

0.83386245968105932

In [17]:
import time
start_time = time.time()

clf_SVM.fit(X_train, Y_train)

print("--- %s seconds ---" % (time.time() - start_time))

--- 446.3740906715393 seconds ---


In [21]:
print(confusion_matrix(Y_test, clf_SVM.predict(X_test)))
clf_SVM.score(X_test,Y_test)

[[6172 1117]
 [1088 5246]]


0.83814137855097992

In [24]:
AMS2(confusion_matrix(Y_test, clf_SVM.predict(X_test)))

1.410238351624477

### Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier

clf_RF = RandomForestClassifier(max_depth=10, n_estimators=100)

cross_val_score(clf_RF, X_train, Y_train, cv=5).mean()

0.8382669190448524

In [118]:
from sklearn.grid_search import GridSearchCV 

import time
start_time = time.time()

param_test2 = {'max_depth':list(range(5,18,3)), 'n_estimators': list(range(50,560,100))}
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(), 

param_grid = param_test2, scoring='roc_auc',n_jobs=4,iid=False, cv=5)

gsearch2.fit(X_train,Y_train)
print(gsearch2.grid_scores_, gsearch2.best_params_, gsearch2.best_score_)

print("--- %s seconds ---" % (time.time() - start_time))

[mean: 0.89645, std: 0.00233, params: {'max_depth': 5, 'n_estimators': 50}, mean: 0.89875, std: 0.00277, params: {'max_depth': 5, 'n_estimators': 150}, mean: 0.89810, std: 0.00181, params: {'max_depth': 5, 'n_estimators': 250}, mean: 0.89854, std: 0.00175, params: {'max_depth': 5, 'n_estimators': 350}, mean: 0.89832, std: 0.00223, params: {'max_depth': 5, 'n_estimators': 450}, mean: 0.89867, std: 0.00256, params: {'max_depth': 5, 'n_estimators': 550}, mean: 0.91150, std: 0.00218, params: {'max_depth': 8, 'n_estimators': 50}, mean: 0.91252, std: 0.00175, params: {'max_depth': 8, 'n_estimators': 150}, mean: 0.91237, std: 0.00169, params: {'max_depth': 8, 'n_estimators': 250}, mean: 0.91250, std: 0.00163, params: {'max_depth': 8, 'n_estimators': 350}, mean: 0.91251, std: 0.00183, params: {'max_depth': 8, 'n_estimators': 450}, mean: 0.91270, std: 0.00172, params: {'max_depth': 8, 'n_estimators': 550}, mean: 0.91694, std: 0.00177, params: {'max_depth': 11, 'n_estimators': 50}, mean: 0.91818

In [119]:
import time
start_time = time.time()

clf_RF = RandomForestClassifier(max_depth=17, n_estimators=550)
clf_RF.fit(X_train, Y_train)

print("--- %s seconds ---" % (time.time() - start_time))

--- 178.1745343208313 seconds ---


In [27]:
import time
start_time = time.time()

clf_RF = RandomForestClassifier(max_depth=14, n_estimators=460)
clf_RF.fit(X_train, Y_train)

print("--- %s seconds ---" % (time.time() - start_time))

--- 318.94792461395264 seconds ---


In [120]:
print(confusion_matrix(Y_test, clf_RF.predict(X_test)))
clf_RF.score(X_test,Y_test)

[[6243 1046]
 [1054 5280]]


0.84584893195331423

In [ ]:
print(confusion_matrix(Y_test, clf_RF.predict(X_test)))
clf_RF.score(X_test,Y_test)

In [29]:
AMS2(confusion_matrix(Y_test, clf_RF.predict(X_test)))

1.4375379896421117

### Logistic Regression with L1 

In [30]:
from sklearn import linear_model


clf_LR = linear_model.LogisticRegression(penalty = 'l1')

cross_val_score(clf_LR, X_train, Y_train, cv=5).mean()

0.72690904361508391

In [61]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000] }

start_time = time.time()
gsearchLR = GridSearchCV(linear_model.LogisticRegression(penalty = 'l1'), param_grid)
gsearchLR.fit(X_train,Y_train)
print("--- %s seconds ---" % (time.time() - start_time))

print(gsearchLR.grid_scores_, gsearchLR.best_params_, gsearchLR.best_score_)

--- 26.493537664413452 seconds ---
[mean: 0.69272, std: 0.00235, params: {'C': 0.001}, mean: 0.72412, std: 0.00356, params: {'C': 0.01}, mean: 0.72623, std: 0.00358, params: {'C': 0.1}, mean: 0.72649, std: 0.00369, params: {'C': 1}, mean: 0.72652, std: 0.00372, params: {'C': 10}, mean: 0.72651, std: 0.00375, params: {'C': 100}, mean: 0.72654, std: 0.00371, params: {'C': 1000}] {'C': 1000} 0.7265419977610982


In [32]:
clf_LR = linear_model.LogisticRegression(penalty = 'l1', C = 10)

start_time = time.time()
clf_LR.fit(X_train, Y_train)
print("--- %s seconds ---" % (time.time() - start_time))

clf_LR.score(X_test, Y_test)

--- 2.7267801761627197 seconds ---


0.73515378404169418

In [33]:
AMS2(confusion_matrix(Y_test, clf_LR.predict(X_test)))

1.0886188852419179

In [34]:
print(clf_LR.coef_)

[[-0.14627826 -0.35027401 -0.39097191  0.97734341 -0.35272446  1.08743364
   0.08510128  0.92388217 -0.17710165  0.01739176 -0.6242672   0.27858583
   0.41437505  0.3116027  -0.01097672  0.00476618  0.63863667 -0.02868211
   0.00332973  0.04388544  0.01341053 -0.32940451 -0.16946223 -0.56399372
   0.01616393  0.00854873 -0.00176151  0.01690086 -0.00812704 -0.09178579]]


### Gradient boost

In [35]:
from sklearn.ensemble import GradientBoostingClassifier

clf_GB = GradientBoostingClassifier(n_estimators=100, max_depth = 10)

cross_val_score(clf_GB, X_train, Y_train, cv=5).mean()

0.8438457526169435

In [36]:
clf_GB.fit(X_train, Y_train)
clf_GB.score(X_test, Y_test)

0.8472436320927843

In [37]:
clf_GB.feature_importances_

array([ 0.14354602,  0.04842325,  0.05389382,  0.02806151,  0.03884063,
        0.04133585,  0.02962076,  0.03487953,  0.03982677,  0.0214564 ,
        0.02224714,  0.03487351,  0.03602483,  0.03658398,  0.02751745,
        0.02750522,  0.0255648 ,  0.02785359,  0.02378209,  0.0289058 ,
        0.02362624,  0.0279786 ,  0.00369708,  0.02218951,  0.02495102,
        0.02958832,  0.02788624,  0.02257992,  0.02710582,  0.01965431])

In [38]:
print(confusion_matrix(Y_test, clf_GB.predict(X_test)))

[[6265 1024]
 [1057 5277]]


In [39]:
AMS2(confusion_matrix(Y_test, clf_GB.predict(X_test)))

1.4503031213072557

In [121]:
from sklearn.ensemble import GradientBoostingClassifier

clf_GB2 = GradientBoostingClassifier(n_estimators=100, max_depth = 10)

cross_val_score(clf_GB2, X_train, Y_train, cv=5).mean()

0.84386411976254527

In [123]:
from sklearn.ensemble import GradientBoostingClassifier

clf_GB = GradientBoostingClassifier(n_estimators=360, max_depth = 20)

cross_val_score(clf_GB, X_train, Y_train, cv=5).mean()

0.8302288479325789

### LDA

In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

clf_LDA = LinearDiscriminantAnalysis()

cross_val_score(clf_LR, X_train, Y_train, cv=5).mean()

0.72689069162389297

In [41]:
start_time = time.time()
clf_LDA.fit(X_train,Y_train)
print("--- %s seconds ---" % (time.time() - start_time))

clf_LDA.score(X_test, Y_test)

--- 3.19126296043396 seconds ---


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:387: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


0.72920795713132203

In [42]:
print(confusion_matrix(Y_test, clf_LDA.predict(X_test)))
clf_LDA.score(X_train,Y_train)

[[5622 1667]
 [2022 4312]]


0.72415628268888443

In [43]:
AMS2(confusion_matrix(Y_test, clf_LDA.predict(X_test)))

1.0721082562629329

### QDA

In [44]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

clf_QDA = QuadraticDiscriminantAnalysis()
cross_val_score(clf_QDA, X_train, Y_train, cv=5).mean()

0.72246795772478478

In [59]:
start_time = time.time()
clf_QDA.fit(X_train,Y_train)
print("--- %s seconds ---" % (time.time() - start_time))

clf_QDA.score(X_test, Y_test)

--- 0.32622718811035156 seconds ---


0.476326800264259

### Naive Bayes

In [46]:
from sklearn.naive_bayes import GaussianNB

clf_NB = GaussianNB()

cross_val_score(clf_LR, X_train, Y_train, cv=5).mean()

0.72692739560627495

In [47]:
start_time = time.time()
clf_NB.fit(X_train, Y_train)
print("--- %s seconds ---" % (time.time() - start_time))


clf_NB.score(X_test, Y_test)

--- 0.17812633514404297 seconds ---


0.73500697350069732

In [48]:
print(confusion_matrix(Y_test, clf_NB.predict(X_test)))

[[5042 2247]
 [1363 4971]]


In [49]:
AMS2(confusion_matrix(Y_test, clf_NB.predict(X_test)))

1.0943368003390268

### Neutral Networks

In [50]:
from sklearn.neural_network import MLPClassifier

layers = 50

start_time = time.time()
clf_NN = MLPClassifier(alpha=1e-5,
                    hidden_layer_sizes=(layers, layers, layers, layers, layers, layers, layers, layers, layers, layers))

print(cross_val_score(clf_NN, X_train, Y_train, cv=5).mean())

print("--- %s seconds ---" % (time.time() - start_time))

0.800994590701
--- 2132.712710618973 seconds ---


In [51]:
clf_NN.fit(X_train, Y_train,)
clf_NN.score(X_test, Y_test)

0.81032078103207805

In [52]:
print(confusion_matrix(Y_test, clf_NN.predict(X_test)))
clf_NN.score(X_train,Y_train)

[[6128 1161]
 [1423 4911]]


0.92969481198730064

In [53]:
AMS2(confusion_matrix(Y_test, clf_NN.predict(X_test)))

1.3254761979858598

### Ensemble Voting

In [62]:
from sklearn.ensemble import VotingClassifier

eclf1 = VotingClassifier(estimators=[
        ('rf', clf_RF),  ('gb', clf_GB), ('nn',clf_NN)
], voting='hard')
eclf1.fit(X_train, Y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=14, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_es...=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False))],
         n_jobs=1, voting='hard', weights=None)

In [63]:
eclf1.score(X_test, Y_test)

0.84746384790427953

In [66]:
eclf2 = VotingClassifier(estimators=[
        ('rf', clf_RF),  ('gb', clf_GB), ('nn',clf_NN), ('LDA', clf_SVM)
], voting='hard')
eclf2.fit(X_train, Y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=14, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_es...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         n_jobs=1, voting='hard', weights=None)

In [67]:
eclf2.score(X_test, Y_test)

0.84951919547823529

In [68]:
eclf3 = VotingClassifier(estimators=[
        ('rf', clf_RF),  ('gb', clf_GB), ('nn',clf_NN), ('LDA', clf_SVM), ('LR', clf_LR)
], voting='hard')
eclf3.fit(X_train, Y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=14, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_es...ty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))],
         n_jobs=1, voting='hard', weights=None)

In [69]:
eclf3.score(X_test, Y_test)

0.84783087425677162

In [76]:
algo = ['SVM', 'RF', 'GB',  'NN']

pred_mat = pd.DataFrame()

In [77]:
pred_mat['SVM'] = clf_SVM.predict(X_train)

In [79]:
pred_mat['RF'] = clf_RF.predict(X_train)
pred_mat['GB'] = clf_GB.predict(X_train)
pred_mat['NN'] = clf_NN.predict(X_train)

In [82]:
clf_stack_LR = linear_model.LogisticRegression(penalty = 'l1')

clf_stack_LR.fit(pred_mat, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [85]:
pred_mat_test = pd.DataFrame()

pred_mat_test['SVM'] = clf_SVM.predict(X_test)
pred_mat_test['RF'] = clf_RF.predict(X_test)
pred_mat_test['GB'] = clf_GB.predict(X_test)
pred_mat_test['NN'] = clf_NN.predict(X_test)

In [87]:
clf_stack_LR.score(pred_mat_test, Y_test)

0.84761065844527639

### Adding predictions as features

In [110]:
Xfeat_train = X_train.copy()

In [112]:
Xfeat_train['SVM'] = clf_SVM.predict(X_train)
Xfeat_train['RF'] = clf_RF.predict(X_train)
Xfeat_train['GB'] = clf_GB.predict(X_train)
Xfeat_train['NN'] = clf_NN.predict(X_train)

In [114]:
clf_LR_feat = linear_model.LogisticRegression(penalty = 'l1')
clf_LR_feat.fit(Xfeat_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [115]:
Xfeat_test = X_test.copy()
Xfeat_test['SVM'] = clf_SVM.predict(X_test)
Xfeat_test['RF'] = clf_RF.predict(X_test)
Xfeat_test['GB'] = clf_GB.predict(X_test)
Xfeat_test['NN'] = clf_NN.predict(X_test)

In [117]:
clf_LR_feat.score(Xfeat_test, Y_test)

0.84746384790427953